site_title = "MyArxiv"
limit_days = 7
cache_url = "https://ZhaoRunning.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.SD"
title = "Sound"

[[sources]]
limit = 150
category = "eess.AS"
title = "Audio and Speech Processing"

[[sources]]
limit = 150
category = "eess.SP"
title = "Signal Processing"

[[sources]]
limit = 150
category = "cs.NI"
title = "Networking and Internet Architecture"

[[sources]]
limit = 150
category = "cs.HC"
title = "Human-Computer Interaction"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
